# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Naré Karapetyan
title2:           Նարե Կարապետյան
tagline:          'A Jekyll theme'
description:      'I am a PhD student at University of South Carolina. I want to build machines that collaborating with each other will help people to learn and work better.'
url:              http://gitbzuk.github.io
baseurl:          /
data:
  baseurl:

author:
  name:           'Nare Karapetyan'
  avatar: 	      cover.jpg
paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

